# Dependabot 設定

version: 2
updates:
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          # update-types を指定せず major も含めて 1 PR へ集約する
          actions:
              patterns: ['*']

    - package-ecosystem: 'nuget'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          nuget:
              patterns: ['*']

    # global.json の SDK のバージョンを更新する
    - package-ecosystem: 'dotnet-sdk'
      directory: '/'
      schedule:
          interval: 'weekly'
